### ISSUE TITLE
FreeCam speed/sensitivity too high

### ISSUE THREAD

**Issue by zephyrnok** [vibeside/FreeCammer#4]
Not sure if it's just in the FPS mode, but the speed of the camera's motion is almost unusable; one tap of the key all but launches the view across the map.  Could movement speed be an item in the config? I assume it's to facilitate looking between moon-side and facility/mansion side, since the facilities "spawn" below the "outdoor" map; maybe a toggle key to change the height by some amount to jump between outdoors & indoors?

**Comment by vibeside** [comment]
using the scroll wheel will allow you to change your speed

**Comment by zephyrnok** [comment]
Ace 👌
